version: '3'

services:
  shop:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kidsgurudb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 6603:3306
    expose:
      - '6603'
    volumes:
      - /data/mysql
  kids-guru:
    image: kids-guru
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - shop
    ports:
      - 8080:8080
    expose:
      - '8080'
    volumes:
      - /data/kids-guru